#!/bin/sh

set -e

REF=$(mktemp /tmp/loop.XXXXXX)
touch "$REF"

trap "rm -f $REF" SIGINT SIGTERM EXIT

while true; do
	changes=$(find src -type f -name '*.rs' -newer "$REF" | wc -l)

	if test "$changes" -eq 0; then
		sleep 1
		continue
	fi

	#if cargo test -- "$@"; then
		cargo run -- "$@" || true
	#fi

	touch "$REF"
	echo
	echo
	echo ------------------------------------------------------------------------
	echo
	echo
done

