use crate::*;

pub const PUZZLES: [aoc::Puzzle; 1] = [
	day01::PUZZLE_DATA,
	//day02::PUZZLE_DATA,
	//day03::PUZZLE_DATA,
	//day04::PUZZLE_DATA,
	//day05::PUZZLE_DATA,
	//day06::PUZZLE_DATA,
	//day07::PUZZLE_DATA,
	//day08::PUZZLE_DATA,
	//day09::PUZZLE_DATA,
	//day10::PUZZLE_DATA,
	//day11::PUZZLE_DATA,
	//day12::PUZZLE_DATA,
	//day13::PUZZLE_DATA,
	//day14::PUZZLE_DATA,
	//day15::PUZZLE_DATA,
	//day16::PUZZLE_DATA,
	//day17::PUZZLE_DATA,
	//day18::PUZZLE_DATA,
	//day19::PUZZLE_DATA,
	//day20::PUZZLE_DATA,
	//day21::PUZZLE_DATA,
	//day22::PUZZLE_DATA,
	//day23::PUZZLE_DATA,
	//day24::PUZZLE_DATA,
	//day25::PUZZLE_DATA,
];

