#!/bin/sh

set -e

source ~/pyenv/aoc/bin/activate

REF=$(mktemp /tmp/loop.XXXXXX)
touch "$REF"

trap "rm -f $REF" SIGINT SIGTERM EXIT

while true; do
	touch "$REF"

	./main.py "$@" || true
		#cargo run -- "$@" || true
	#fi

	while test "$(find . -type f -name '*.py' -newer "$REF" | wc -l)" -eq 0; do
		sleep 1
	done

	echo
	echo
	echo ------------------------------------------------------------------------
	echo
	echo
done

